#!/usr/bin/env bash

# Determine the directory where the script is located
SCRIPT_DIR="$(dirname -- "$0")"

# Add the script directory to the PYTHONPATH
export PYTHONPATH="$SCRIPT_DIR:$PYTHONPATH"

# Run the frontend module with the provided arguments
python -m src.frontend "$@"
