[book]
authors = ["David A. Samson"]
language = "en"
multilingual = false
src = "src"
title = "Learning Dewy"

[build]
build-dir = "book"

[output.html]
default-theme = "dewy-light"
preferred-dark-theme = "dewy-dark"
additional-css = ["theme/dewy-book.css"]
additional-js = ["theme/dewy-book.js"]
git-repository-url = "https://github.com/david-andrew/dewy-lang"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/david-andrew/dewy-lang/edit/master/site/learn/{path}"
site-url = "/dewy-lang/learn/"
