"""Generate the checked-in Unicode grapheme property tables."""

from hashlib import sha256
from pathlib import Path
from urllib.request import urlopen


UNICODE_VERSION = '16.0.0'
HERE = Path(__file__).parent
SOURCES = {
    'GraphemeBreakProperty.txt': (
        f'https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/auxiliary/'
        'GraphemeBreakProperty.txt',
        'c29360bd6f7132811d701d29069541e827eb44bfc4c8fbde8c370d6982689dc1',
    ),
    'emoji-data.txt': (
        f'https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/emoji/'
        'emoji-data.txt',
        'f1365a5173eee18e1f98b240cdc492e84a25f1ce7e0c9d1094eb29c41a22696a',
    ),
    'DerivedCoreProperties.txt': (
        f'https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/'
        'DerivedCoreProperties.txt',
        '39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd',
    ),
    'GraphemeBreakTest.txt': (
        f'https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/auxiliary/'
        'GraphemeBreakTest.txt',
        'ee2b9354d270ac061b29f09662cafea06341d77e704b8cc6bd72aaeeda363cb5',
    ),
}


def _download(name: str) -> str:
    url, expected_hash = SOURCES[name]
    content = urlopen(url).read()
    actual_hash = sha256(content).hexdigest()
    if actual_hash != expected_hash:
        raise ValueError(
            f'{name} SHA-256 is {actual_hash}, expected {expected_hash}'
        )
    return content.decode()


def _code_point_range(field: str) -> tuple[int, int]:
    endpoints = field.split('..')
    start = int(endpoints[0], 16)
    end = int(endpoints[-1], 16)
    return start, end


def _property_ranges(
    source: str,
    property_name: str | None = None,
) -> list[tuple[int, int, str]]:
    ranges: list[tuple[int, int, str]] = []
    for raw_line in source.splitlines():
        line = raw_line.split('#', 1)[0].strip()
        if not line:
            continue
        fields = [field.strip() for field in line.split(';')]
        if property_name is None:
            value = fields[1]
        elif len(fields) >= 3 and fields[1] == property_name:
            value = fields[2]
        else:
            continue
        start, end = _code_point_range(fields[0])
        ranges.append((start, end, value))

    ranges.sort()
    merged: list[tuple[int, int, str]] = []
    for start, end, value in ranges:
        if merged and merged[-1][1] + 1 == start and merged[-1][2] == value:
            previous_start, _, _ = merged[-1]
            merged[-1] = previous_start, end, value
        else:
            merged.append((start, end, value))
    return merged


def _format_ranges(
    name: str,
    ranges: list[tuple[int, int, str]],
) -> list[str]:
    lines = [f'{name}: tuple[tuple[int, int, str], ...] = (']
    lines.extend(
        f"    (0x{start:X}, 0x{end:X}, '{value}'),"
        for start, end, value in ranges
    )
    lines.append(')')
    return lines


def generate() -> None:
    grapheme_break = _property_ranges(_download('GraphemeBreakProperty.txt'))
    emoji = _property_ranges(_download('emoji-data.txt'))
    extended_pictographic = [
        entry for entry in emoji if entry[2] == 'Extended_Pictographic'
    ]
    indic_conjunct = _property_ranges(
        _download('DerivedCoreProperties.txt'),
        'InCB',
    )

    lines = [
        '"""Generated Unicode 16.0.0 properties used by UAX #29 segmentation.',
        '',
        'Generated by generate.py; do not edit manually.',
        '"""',
        '',
        f"UNICODE_VERSION = '{UNICODE_VERSION}'",
        '',
        *_format_ranges('GRAPHEME_BREAK_RANGES', grapheme_break),
        '',
        *_format_ranges(
            'EXTENDED_PICTOGRAPHIC_RANGES',
            extended_pictographic,
        ),
        '',
        *_format_ranges('INDIC_CONJUNCT_BREAK_RANGES', indic_conjunct),
        '',
    ]
    (HERE / 'data.py').write_text('\n'.join(lines))

    test_data = HERE.parents[3] / 'tests' / 'data'
    test_data.mkdir(exist_ok=True)
    (test_data / f'GraphemeBreakTest-{UNICODE_VERSION}.txt').write_text(
        _download('GraphemeBreakTest.txt')
    )


if __name__ == '__main__':
    generate()
