"""
semantic analysis pass 0: 
- type checking
- ambiguity resolution
"""
from dataclasses import dataclass, replace, field
from collections import ChainMap
from ..parser import p0, t2, t1, t0
from . import hir, ty, builtins
from ..reporting import SrcFile, ReportException, Error, Pointer, Span
from typing import Callable, Literal


import pdb

@dataclass
class Context:
    """global context for the typechecker"""
    srcfile: SrcFile
    declarations: ChainMap[str, ty.Type] = field(default_factory=ChainMap) #TODO: handling different scopes...
    type_system: ty.TypeSystem = field(default_factory=ty.TypeSystem)
    # TODO: etc stuff

def typecheck_and_resolve(srcfile: SrcFile) -> hir.AST:
    # set up the base type system/builtins
    type_system = ty.TypeSystem()
    builtins.apply_builtin_promote_rules(type_system)
    declarations = ChainMap(builtins.builtin_types)
    
    ctx = Context(srcfile, declarations, type_system)
    block = p0.parse(srcfile)
    return tcr_block(block, ctx=ctx)

def try_in_comprehension(f:Callable, *args, **kwargs):
    """allow exception-raising functions to be used in comprehensions by capturing the exception as a value rather than raising it upwards"""
    try:
        return f(*args, **kwargs)
    except Exception as e:
        return e

def typecheck_and_resolve_inner(ast: p0.AST, *, ctx: Context, type_block:bool=False) -> hir.AST:
    match ast:
        case p0.Ambiguous(candidates=candidates):
            passes = [try_in_comprehension(typecheck_and_resolve_inner, candidate, ctx=ctx, type_block=type_block) for candidate in candidates]
            passes = [p for p in passes if not isinstance(p, (ValueError, ReportException))] #TODO: filter for only exceptions that can be generated by typecheck process
            errors = [p for p in passes if isinstance(p, Exception)]
            assert len(errors) == 0, f'INTERNAL ERROR: Ambiguous AST {ast} produced {len(errors)} non-typechecking-related errors: {errors=}. {passes=}'
            if len(passes) == 0:
                # TODO: full user error report
                raise ValueError(f'USER ERROR: Ambiguous AST {ast} has no valid options: {passes=}. {ast=}')
            if len(passes) > 1:
                # TODO: full user error report
                raise ValueError(f'USER ERROR: Ambiguous AST {ast} has too many valid options that could not be disambiguated: {passes=}. {ast=}')
            return passes[0]

        
        case p0.KeywordExpr(parts=[t1.Keyword(name='let'|'const'), *_]):
            return tcr_declare(ast, ctx=ctx)

        case p0.KeywordExpr(parts=[t1.Keyword(name='import'|'from'), *_]):
            return tcr_import(ast, ctx=ctx)
        
        case p0.KeywordExpr(parts=[t1.Keyword(name='return'), *_]):
            return tcr_return(ast, ctx=ctx)

        # etc. keyword cases as outlined in t2
        # final catch-all case (internal error since t2 shouldn't produce anything like this)
        case p0.KeywordExpr():
            pdb.set_trace()
            raise ValueError(f'NOT IMPLEMENTED -OR- INTERNAL ERROR: unrecognized keyword expression structure: {ast=}')

        case p0.BinOp(op=t1.Operator(symbol=':='|'='|'::')):
            return tcr_assign(ast, ctx=ctx)

        case p0.Block(): return tcr_block(ast, ctx=ctx)
        case p0.BinOp(): return tcr_binop(ast, ctx=ctx, type_block=type_block)
        case p0.Atom(item=t1.Identifier(name='..')): return hir.Range(ast.item.loc, 'range', bounds=None, step_pair=None, left=None, right=None)
        case p0.Atom(item=t1.Identifier()): return tcr_identifier(ast.item, ctx=ctx)
        case p0.Atom(item=t1.String(content=content)): return hir.String(ast.item.loc, 'string', content)
        case p0.Atom(item=t1.Integer(value=value)): return hir.Integer(ast.item.loc, 'int', value.prefix, t0.parse_integer(value.src, value.prefix))
        # case p0.Atom(item=t1.Real()): ...
        # case p0.Atom(item=t1.BasedString()): ...
        # case p0.Atom(item=t1.Semicolon()): ...
        # case p0.Atom(item=t1.Metatag()): ...
        # case p0.Atom(item=t1.Integer()): ...
        case p0.Atom(item=t1.Bool(value=value)): return hir.Bool(ast.item.loc, 'bool', value)
        # case p0.Atom(item=t2.OpFn()): ...
        # case p0.Atom(item=t2.Placeholder()): ...
        case p0.Flat(op=t2.RangeJuxtapose()): return tcr_bare_range(ast, ctx=ctx)
        case _:
            pdb.set_trace()
            raise NotImplementedError(f'typecheck_and_resolve_inner not implemented for {type(ast)}')


def tcr_declare(ast: p0.KeywordExpr, *, ctx: Context) -> hir.AST:
    """
    let|const <id>
    let|const <id> = <expr>
    let|const <id>:<typeexpr>
    let|const <id>:<typeexpr> = <expr>

    TODO := and ::

    basically 4 parameters:
    - let vs const
    - typed vs untyped
    - = vs := vs ::   (though := is a bit of a special case since it doesn't need let or const)
    - expr vs undefined

    """
    # typeexpr = None
    # right = None
    # compiletime = False
    # keyword = ast.parts[0].name
    # assert keyword in ['let', 'const'], f'INTERNAL ERROR: invalid keyword: {keyword}'




    match ast.parts:
        case [
            t1.Keyword(name='let'|'const' as keyword), 
            p0.BinOp(
                left=p0.Atom(item=t1.Identifier(name=name)), 
                op=t1.Operator(symbol='='|'::'|':=' as op),
                right=p0.AST() as right)
            ]:
            expr = typecheck_and_resolve_inner(right, ctx=ctx)
            #TODO: perhaps special handling if expr.type is VOID_TYPE.
            #      also it shouldn't be possible for it to be inferred type, but may need to check/handle...
            
            # use the type directly from the expression since no type annotation was provided
            ctx.declarations[name] = expr.type

            return hir.Declare(ast.loc, ty.VOID_TYPE, keyword, name, expr)
        
        case [
            t1.Keyword(name='let'|'const'),
            p0.BinOp(
                left=p0.BinOp(
                    left=p0.Atom(item=t1.Identifier(name=name)),
                    op=t1.Operator(symbol=':'),
                    right=p0.AST() as typeexpr),
                op=t1.Operator(symbol='='|'::'|':=' as op),
                right=p0.AST() as right)
            ]:
            # decl assign + type annotation
            pdb.set_trace()
        
        case [
            t1.Keyword(name='let'|'const'),
            p0.Atom(item=t1.Identifier(name=name))
        ]:
            # decl only
            pdb.set_trace()
        case [
            t1.Keyword(name='let'|'const'),
            p0.BinOp(
                left=p0.Atom(item=t1.Identifier(name=name)),
                op=t1.Operator(symbol=':'),
                right=p0.AST() as typeexpr
            ),
        ]:
            # decl only + type annotation
            pdb.set_trace()
        case _:
            pdb.set_trace()


        # case p0.BinOp(op=t1.Operator(symbol='='), left=p0.Atom(item=t1.Identifier(name=name)), right=p0.AST() as right):
        #     resolved_expr = typecheck_and_resolve_inner(right, ctx=ctx)
        #     pdb.set_trace()
        #     return hir.Decl(kind, name, resolved_expr.type, resolved_expr)
        # case p0.BinOp(op=t1.Operator(symbol='='), left=p0.BinOp(op=t1.Operator(symbol=':'), left=p0.Atom(item=t1.Identifier(name=name)), right=p0.AST() as typeexpr), right=p0.AST() as expr):
        #     pdb.set_trace()
        
    
    
    pdb.set_trace()

def tcr_assign(ast: p0.BinOp, *, ctx: Context) -> hir.AST:
    """
    non-declare assignments, e.g. `name=value`
    compiletime assignments, e.g. `name::value`
    implicit declarations, e.g. `name:=value`
    """
    pdb.set_trace()

def tcr_import(ast: p0.KeywordExpr, *, ctx: Context) -> hir.AST:
    pdb.set_trace()

def tcr_return(ast: p0.KeywordExpr, *, ctx: Context) -> hir.AST:
    if len(ast.parts) > 2: raise ValueError(f'INTERNAL ERROR: return statement may only contain zero or one expression, got {len(ast.parts)}. {ast.parts=}. (should have been caught during p0 phase)')
    if len(ast.parts) == 1:
        return hir.Return(ast.parts[0].loc, ty.VOID_TYPE)
    item = typecheck_and_resolve_inner(ast.parts[1], ctx=ctx)
    return hir.Return(ast.parts[0].loc, ty.VOID_TYPE, item)

def tcr_block(block: p0.Block, *, ctx: Context) -> hir.AST:
    # TODO: if kind=='<>' then typecheck and resolve needs to behave differently, e.g. because `|` means `type union`, not regular `or`
    # scoped = block.kind == '{}' #TODO: would need to make a nested scope/context for this...

    # open a new scope if the block is a scoped block
    type_block = block.kind == '<>'
    if block.kind == '{}': ctx = replace(ctx, declarations=ctx.declarations.new_child())

    # typecheck and resolve the inner items
    results = [typecheck_and_resolve_inner(item, ctx=ctx, type_block=type_block) for item in block.inner]

    match block.kind:
        case '()':
            if len(results) > 1:
                return hir.Block(block.loc, results, scoped=False)
            if len(results) == 1:
                item = results[0]
                if isinstance(item, hir.Range) and item.bounds is None:
                    return replace(item, loc=block.loc, bounds=block.kind)
                return item
            return hir.Void(block.loc)
        
        case '{}':
            if len(results) > 1:
                pdb.set_trace()
                return hir.Block(block.loc, ty.BlockType, results, scoped=True) #TODO: parameterize block type based on inner content... e.g. tuple of types
            if len(results) == 1:
                return hir.Block(block.loc, results[0].type, results, scoped=True)
            return hir.Void(block.loc)

        case '[]':
            if len(results) == 1 and isinstance(results[0], hir.Range) and results[0].bounds is None:
                return replace(results[0], loc=block.loc, bounds=block.kind)
            # otherwise it may be an array. also arrays should handle multi-dimensions via spacing, nested arrays, ;, etc.
            # might also be a generator...
            pdb.set_trace()
        case '[)':
            if len(results) != 1 or not isinstance(results[0], hir.Range) or results[0].bounds is not None:
                # TODO: full user error report
                raise ValueError(f'USER ERROR: [) delimiter for range may only contain one (bare range) expression, got {len(results)}. {results=}')
            return replace(results[0], loc=block.loc, bounds=block.kind)
        case '(]':
            if len(results) != 1 or not isinstance(results[0], hir.Range) or results[0].bounds is not None:
                # TODO: full user error report
                raise ValueError(f'USER ERROR: (] delimiter for range may only contain one (bare range) expression, got {len(results)}. {results=}')
            return replace(results[0], loc=block.loc, bounds=block.kind)
        case '<>':
            # return hir.TypeBlock(block.loc, type..., results) #TODO: handling type of type block based on contained inner items
            pdb.set_trace()
        case _:
            # unreachable
            raise ValueError(f'INTERNAL ERROR: invalid block kind: {block.kind}')
        
    # unreachable 
    pdb.set_trace()

def tcr_binop(binop: p0.BinOp, *, ctx: Context, type_block:bool=False) -> hir.AST:
    """
    typecheck and resolve a binary operator node.
    
    NOTE:
    type_block is used to disambiguate the context these binops occur in. 
    mainly for distinguishing type expressions using literals from regular operations between said literals
    e.g. `true | false` -> `true` vs `<true | false>` -> `literal<true>|literal<false>`
    most other operators are unaffected by this flag.
    """

    # Special cases that don't just typecheck both sides
    if binop.op.symbol == '=>': return tcr_function_literal(binop, ctx=ctx)

    if binop.op.symbol in ('=','::',':='):
        #TODO: determine if assignment or declaration based on if the right already declared
        right = typecheck_and_resolve_inner(binop.right, ctx=ctx)
        target = tcr_assignment_target(binop.left, right, ctx=ctx)
        pdb.set_trace()

    if isinstance(binop.op, t2.CallJuxtapose):
        left = typecheck_and_resolve_inner(binop.left, ctx=ctx, type_block=type_block)
        return tcr_function_call(left, binop.right, ctx=ctx)

    # TODO: other more specialized structures (e.g. assignment, spread, collect, parameterization, etc.)


    # regular cases where left and right are both normal expressions
    # TODO: how to handle the fact that `and` and `or` might have inner elements that need type_block? for now just pass in to left and right
    # full expression
    left = typecheck_and_resolve_inner(binop.left, ctx=ctx, type_block=type_block)
    right = typecheck_and_resolve_inner(binop.right, ctx=ctx, type_block=type_block)
    
    match binop.op:
        case t2.QJuxtapose():
            pdb.set_trace()
        case t2.IndexJuxtapose():
            pdb.set_trace()
        case t2.MultiplyJuxtapose():
            # TODO: need table for binop compatibility
            pdb.set_trace()
        case t2.RangeJuxtapose(): pdb.set_trace()
        case t2.EllipsisJuxtapose(): pdb.set_trace()
        case t2.TypeParamJuxtapose(): pdb.set_trace()
        case t2.SemicolonJuxtapose(): pdb.set_trace()
        case t2.CombinedAssignmentOp(): pdb.set_trace()
        case t2.InvertedComparisonOp(): pdb.set_trace()
        case t2.BroadcastOp(): pdb.set_trace()
    
    # TODO: eventually should be able to remove this check once all the arms of the above match are implemented
    assert isinstance(binop.op, t1.Operator), f'INTERNAL ERROR: unexpected operator type: {binop.op}'



    if binop.op.symbol in builtins.BINOP_DUNDER_MAP:
        fname = builtins.BINOP_DUNDER_MAP[binop.op.symbol]
        ftype = ctx.declarations[fname]
        assert isinstance(ftype, (ty.FunctionType, ty.OverloadType)), f'INTERNAL ERROR: builtin function type expected, got {type(ftype)}'
        methods = ftype.methods if isinstance(ftype, ty.OverloadType) else [ftype]
        try:
            result = ctx.type_system.match_best_function(methods, [left.type, right.type])
        except ty.DispatchError as e:
            raise ValueError(f'USER ERROR: {e} for binop {binop.op.symbol!r}') from e
        left_arg, right_arg = apply_promotions([left, right], result.promote_pos)
        return hir.FunctionCall(
            Span(left.loc.start, right.loc.stop),
            result.method.ret,
            hir.ExpressedIdentifier(binop.op.loc, result.method, fname),
            [left_arg, right_arg],
            {},
        )

    match binop.op.symbol:
        # case '+': return tcr_add(left, right)
        case 'and' | '&':
            # `and` and `&` are the same operator; meaning is selected by operand types
            # (bitwise, logical, type intersect in type position, overload combine for callables, …).
            # Full resolution should go through the dispatch system; handle callables here for now.
            if isinstance(left.type, (ty.FunctionType, ty.OverloadType)) and isinstance(right.type, (ty.FunctionType, ty.OverloadType)):
                left_methods = left.type.methods if isinstance(left.type, ty.OverloadType) else [left.type]
                right_methods = right.type.methods if isinstance(right.type, ty.OverloadType) else [right.type]
                combined = ty.OverloadType(left_methods + right_methods)
                # Reuse left as a carrier until a dedicated HIR Overload node exists.
                return replace(left, loc=Span(left.loc.start, right.loc.stop), type=combined)
            # TODO: dispatch __and__ for int/bool/etc. (same path as other binops)
            pdb.set_trace()
            raise NotImplementedError(f'tcr_binop and/& not yet implemented for operand types: {left.type=}, {right.type=}')
        # case '-': return tcr_sub(left, right)
        # case '*': return tcr_mul(left, right)
        # case '/': return tcr_div(left, right)
        # case '%': return tcr_mod(left, right)
        # case '//': return tcr_floordiv(left, right)
        # case '^': return tcr_pow(left, right)
        # case '<<': return tcr_lshift(left, right)
        # case '>>': return tcr_rshift(left, right)
        
        
        
        case _:
            pdb.set_trace()
            raise NotImplementedError(f'tcr_binop not implemented for {type(binop.op)}')








    pdb.set_trace()

def tcr_assignment_target(target: p0.AST, right: hir.AST, *, ctx: Context):  # -> UndeclaredIdentifier|Identifier|Unpack|ArrayRangeTarget|etc.
    """
    verify that the assignment target is valid and can receive the right-hand side expression
    """
    pdb.set_trace()

def tcr_bare_range(ast: p0.Flat, *, ctx: Context) -> hir.Range:
    """
    typecheck and resolve a bare range expression, e.g. `1..2`
    """
    # collect the left and right items
    match ast.items:
        case [left, p0.Atom(item=t1.Identifier(name='..')), right]: ...
        case [p0.Atom(item=t1.Identifier(name='..')), right]:
            left = None #hir.Void(Span(ast.loc.start, ast.loc.start), type=ty.VOID_TYPE)
        case [left, p0.Atom(item=t1.Identifier(name='..'))]:
            right = None #hir.Void(Span(ast.loc.stop, ast.loc.stop), type=ty.VOID_TYPE)
        case _:
            pdb.set_trace()
            #TODO: raise full error. this shouldn't be possible to reach.
    
    left = typecheck_and_resolve_inner(left, ctx=ctx) if left is not None else None
    right = typecheck_and_resolve_inner(right, ctx=ctx) if right is not None else None
    #TODO: handle if left or right have comma, split out step pair
    pdb.set_trace()
    return hir.Range(ast.loc, bounds=None, step_pair=None, left=left, right=right)



def typefunc_from_hir_params(
    pos_or_kw_args: list[hir.Param],
    kw_only_args: list[hir.Param | hir.BoundParam],
    rest_args: hir.Param | hir.BoundParam | None,
    rettype: ty.Type,
) -> ty.FunctionType:
    pos = [ty.PosOrKwArg(p.name, p.type if p.type != ty.INFERRED_TYPE else ty.TOP_TYPE) for p in pos_or_kw_args]
    kw: list[ty.KwOnlyArg] = []
    for p in kw_only_args:
        ptype = p.type if p.type != ty.INFERRED_TYPE else ty.TOP_TYPE
        required = not isinstance(p, hir.BoundParam)
        kw.append(ty.KwOnlyArg(p.name, ptype, required))
    rest_name = rest_args.name if rest_args is not None else None
    ret = rettype if rettype != ty.INFERRED_TYPE else ty.TOP_TYPE
    return ty.FunctionType(pos, kw, rest_name, ret)


def tcr_function_literal(binop: p0.BinOp, *, ctx: Context) -> hir.FunctionLiteral:
    """
    function literal: `args => body`
    """
    #analyze the signature
    signature = binop.left
    rettype: ty.Type = ty.INFERRED_TYPE
    
    # if the return type was annotated, capture it
    if isinstance(signature, p0.BinOp) and signature.op.symbol == ':>':
        rettype = ast_to_type(signature.right, ctx=ctx)
        signature = signature.left
    
    # collect function signature parameters
    pos_or_kw_args, kw_only_args, rest_args = collect_function_signature_args(signature, ctx=ctx)

    # TODO: probably inline this helper since it's only used once here
    ftype = typefunc_from_hir_params(pos_or_kw_args, kw_only_args, rest_args, rettype)

    # insert the arguments from the signature into the body
    inner_scope = ctx.declarations.new_child()
    for param in pos_or_kw_args:
        inner_scope[param.name] = param.type
    for param in kw_only_args:
        inner_scope[param.name] = param.type
    if rest_args is not None:
        inner_scope[rest_args.name] = rest_args.type
    inner_ctx = replace(ctx, declarations=inner_scope)
    body = typecheck_and_resolve_inner(binop.right, ctx=inner_ctx)

    return hir.FunctionLiteral(binop.loc, ftype, pos_or_kw_args, kw_only_args, rest_args, rettype, body)

def ast_to_type(ast: p0.AST, *, ctx: Context) -> ty.Type:
    """convert an AST from a position that is expected to be a type into a type"""
    match ast:
        case p0.Atom(item=t1.Identifier(name=name)):
            return name
        
        case p0.BinOp(op=t1.Operator(symbol='or'|'|')):
            left = ast_to_type(ast.left, ctx=ctx)
            right = ast_to_type(ast.right, ctx=ctx)
            if isinstance(left, ty.TypeOr) and isinstance(right, ty.TypeOr):
                return ty.TypeOr(left.items + right.items)
            elif isinstance(left, ty.TypeOr):
                return ty.TypeOr(left.items + [right])
            elif isinstance(right, ty.TypeOr):
                return ty.TypeOr([left] + right.items)
            return ty.TypeOr([left, right])
        
        case p0.BinOp(op=t1.Operator(symbol='and'|'&')):
            left = ast_to_type(ast.left, ctx=ctx)
            right = ast_to_type(ast.right, ctx=ctx)
            if isinstance(left, ty.TypeAnd) and isinstance(right, ty.TypeAnd):
                return ty.TypeAnd(left.items + right.items)
            elif isinstance(left, ty.TypeAnd):
                return ty.TypeAnd(left.items + [right])
            elif isinstance(right, ty.TypeAnd):
                return ty.TypeAnd([left] + right.items)
            return ty.TypeAnd([left, right])
        
        case p0.Prefix(op=t1.Operator(symbol='not'|'~')):
            item = ast_to_type(ast.item, ctx=ctx)
            return ty.TypeNot(item)
        
        # e.g. probably parameterizations (type jux), types wrapped in blocks, etc. other type expressions...
        # also catch all probably involves typecheck_and_resolve_inner(ast, ctx=ctx, type_block=True)
        case _:
            pdb.set_trace()
            raise NotImplementedError(f'ast_to_type not implemented for {type(ast)}')
    
    pdb.set_trace()

def collect_function_signature_args(signature: p0.AST, *, ctx: Context) -> tuple[list[hir.Param], list[hir.Param|hir.BoundParam], hir.Param|hir.BoundParam|None]:
    """
    collect the parameters from a function signature
    
    Returns:
        list of positional or keyword parameters (all unbound)
        list of keyword only parameters (bound or unbound)
        ...rest parameter (if any) or None (bound or unbound)
    """

    # make sure we are operating on a block at the top level
    if not isinstance(signature, p0.Block): return collect_function_signature_args(p0.Block(signature.loc, [signature], kind='()'))

    pos_or_kw_args: list[hir.Param] = []
    kw_only_args: list[hir.Param|hir.BoundParam] = []
    saw_rest: bool = False
    rest_args: hir.Param|hir.BoundParam|None = None
    for item in signature.inner:
        match item:
            case p0.Atom(item=t1.Identifier(name='...')):
                if saw_rest: raise ValueError(f'USER ERROR: ellipsis (...) may only appear once in a function signature, got {item=}. {signature=}')
                saw_rest = True
            case p0.Atom(item=t1.Identifier(name=name)):
                (kw_only_args if saw_rest else pos_or_kw_args).append(hir.Param(name, type=ty.INFERRED_TYPE))
            case p0.BinOp(op=t1.Operator(symbol=':'), left=p0.Atom(item=t1.Identifier(name=name))):
                (kw_only_args if saw_rest else pos_or_kw_args).append(hir.Param(name, type=ast_to_type(item.right, ctx=ctx)))
            case p0.BinOp(op=t1.Operator(symbol='='), left=p0.Atom(item=t1.Identifier(name=name)), right=p0.AST() as right):
                kw_only_args.append(hir.BoundParam(name, type=ty.INFERRED_TYPE, value=typecheck_and_resolve_inner(right, ctx=ctx)))
            case p0.BinOp(op=t1.Operator(symbol='='), left=p0.BinOp(op=t1.Operator(symbol=':'), left=p0.Atom(item=t1.Identifier(name=name)), right=p0.AST() as typeexpr), right=p0.AST() as right):
                kw_only_args.append(hir.BoundParam(name, type=ast_to_type(typeexpr, ctx=ctx), value=typecheck_and_resolve_inner(right, ctx=ctx)))
            case p0.BinOp(op=t2.EllipsisJuxtapose(), left=p0.Atom(item=t1.Identifier(name='...')), right=p0.Atom(item=t1.Identifier(name=name))):
                if saw_rest: raise ValueError(f'USER ERROR: ellipsis (...) may only appear once in a function signature, got {item=}. {signature=}')
                saw_rest = True
                rest_args = hir.Param(name, type=ty.INFERRED_TYPE)
            # case ...name:type
            # case ...name=value
            # case ...name:type=value
            # etc. etc. many other cases... namely dict/object/array unpacking
            case _:
                pdb.set_trace()
                raise NotImplementedError(f'collect_function_signature_args not implemented for {type(item)}')

    return pos_or_kw_args, kw_only_args, rest_args


def parse_call_arguments(right: p0.AST, *, ctx: Context) -> tuple[list[hir.AST], dict[str, hir.AST]]:
    """Typecheck call args from p0, splitting positional vs `name=value` keywords."""
    if isinstance(right, p0.Block):
        items = list(right.inner)
    else:
        items = [right]

    pos_args: list[hir.AST] = []
    kw_args: dict[str, hir.AST] = {}
    for item in items:
        match item:
            case p0.BinOp(op=t1.Operator(symbol='='), left=p0.Atom(item=t1.Identifier(name=name)), right=value):
                if name in kw_args:
                    raise ValueError(f'USER ERROR: duplicate keyword argument "{name}"')
                kw_args[name] = typecheck_and_resolve_inner(value, ctx=ctx)
            case _:
                pos_args.append(typecheck_and_resolve_inner(item, ctx=ctx))
    return pos_args, kw_args


def tcr_function_call(left: hir.AST, right: p0.AST, *, ctx: Context) -> hir.FunctionCall:
    methods: list[ty.FunctionType]
    if isinstance(left.type, ty.FunctionType):
        methods = [left.type]
    elif isinstance(left.type, ty.OverloadType):
        methods = left.type.methods
    else:
        raise ValueError(f'USER ERROR: Expected a function, got {left.type} for call expression {left=}, {right=}')

    pos_args, kw_args = parse_call_arguments(right, ctx=ctx)
    pos_types = [a.type for a in pos_args]
    kw_types = {k: v.type for k, v in kw_args.items()}
    try:
        result = ctx.type_system.match_best_function(methods, pos_types, kw_types)
    except ty.DispatchError as e:
        raise ValueError(f'USER ERROR: {e} for call {left=}, {right=}') from e

    return hir.FunctionCall(
        Span(left.loc.start, right.loc.stop),
        result.method.ret,
        left,
        apply_promotions(pos_args, result.promote_pos),
        kw_args,
    )


def apply_promotions(args: list[hir.AST], promote_pos: list[ty.TypeExpr | None]) -> list[hir.AST]:
    """Wrap args that need promotion in Cast nodes. `promote_pos` is parallel to `args`."""
    out: list[hir.AST] = []
    for arg, target in zip(args, promote_pos):
        if target is None:
            out.append(arg)
        else:
            out.append(hir.ValueCast(arg.loc, target, arg))
    return out


def typecheck_partial_eval(left: hir.AST, right: hir.AST) -> hir.Partial:
    pdb.set_trace()

def tcr_identifier(id: t1.Identifier, *, ctx: Context) -> hir.AST:
    if id.name in ctx.declarations:
        return hir.ExpressedIdentifier(id.loc, ctx.declarations[id.name], id.name)
    
    pdb.set_trace()
    raise NotImplementedError(f'Identifier "{id.name}" not found in context')





def test():
    from ...myargparse import ArgumentParser
    from pathlib import Path
    parser = ArgumentParser()
    parser.add_argument('path', type=Path, required=True, help='path to file to tokenize')
    args = parser.parse_args()
    path: Path = args.path
    src = path.read_text()
    srcfile = SrcFile(path, src)
    try:
        ast = typecheck_and_resolve(srcfile)
    except ReportException as e:
        print(e.report)
        exit(1)
    
    # TODO: some sort of tree print for HIR
    print(ast)
    
if __name__ == '__main__':
    test()