"""
semantic analysis pass 0: 
- type checking
- ambiguity resolution
"""
from dataclasses import dataclass, replace
from ..parser import p0, t2, t1
from . import hir, ty
from ..reporting import SrcFile, ReportException, Error, Pointer, Span
from typing import Callable


import pdb

@dataclass
class Context:
    """global context for the typechecker"""
    srcfile: SrcFile
    declarations: dict[str, ty.Type] #TODO: handling different scopes...
    # TODO: etc stuff

def typecheck_and_resolve(srcfile: SrcFile) -> hir.AST:
    ctx = Context(srcfile, {
        'printf': ty.TypeFunc(args=['string'], ret=ty.VOID_TYPE),
    })
    block = p0.parse(srcfile)
    return tcr_block(block, ctx=ctx)

def try_in_comprehension(f:Callable, *args, **kwargs):
    try:
        return f(*args, **kwargs)
    except Exception as e:
        return e

def typecheck_and_resolve_inner(ast: p0.AST, *, ctx: Context, type_block:bool=False) -> hir.AST:
    match ast:
        case p0.Ambiguous(candidates=candidates):
            passes = [try_in_comprehension(typecheck_and_resolve_inner, candidate, ctx=ctx, type_block=type_block) for candidate in candidates]
            passes = [p for p in passes if not isinstance(p, (ValueError, ReportException))] #TODO: filter for only exceptions that can be generated by typecheck process
            errors = [p for p in passes if isinstance(p, Exception)]
            assert len(errors) == 0, f'INTERNAL ERROR: Ambiguous AST {ast} produced {len(errors)} non-typechecking-related errors: {errors=}. {passes=}'
            if len(passes) == 0:
                # TODO: full user error report
                raise ValueError(f'USER ERROR: Ambiguous AST {ast} has no valid options: {passes=}. {ast=}')
            if len(passes) > 1:
                # TODO: full user error report
                raise ValueError(f'USER ERROR: Ambiguous AST {ast} has too many valid options that could not be disambiguated: {passes=}. {ast=}')
            return passes[0]

        case p0.Block(): return tcr_block(ast, ctx=ctx)
        case p0.BinOp(): return tcr_binop(ast, ctx=ctx, type_block=type_block)
        case p0.Atom(item=t1.Identifier()): return tcr_identifier(ast.item, ctx=ctx)
        case p0.Atom(item=t1.String(content=content)): return hir.String(ast.item.loc, 'string', content)
        # case p0.Atom(item=t1.Real()): ...
        # case p0.Atom(item=t1.BasedString()): ...
        # case p0.Atom(item=t1.Semicolon()): ...
        # case p0.Atom(item=t1.Metatag()): ...
        # case p0.Atom(item=t1.Integer()): ...
        case p0.Atom(item=t1.Bool(value=value)): return hir.Bool(ast.item.loc, 'bool', value)
        # case p0.Atom(item=t2.OpFn()): ...
        case _:
            pdb.set_trace()
            raise NotImplementedError(f'typecheck_and_resolve_inner not implemented for {type(ast)}')


def tcr_block(block: p0.Block, *, ctx: Context) -> hir.AST:
    # TODO: if kind=='<>' then typecheck and resolve needs to behave differently, e.g. because `|` means `type union`, not regular `or`
    type_block = block.kind == '<>'
    # scoped = block.kind == '{}' #TODO: would need to make a nested scope/context for this...
    results = [typecheck_and_resolve_inner(item, ctx=ctx, type_block=type_block) for item in block.inner]

    match block.kind:
        case '()':
            if len(results) > 1:
                return hir.Block(block.loc, results, scoped=False)
            if len(results) == 1:
                item = results[0]
                if isinstance(item, hir.Range) and item.bounds is None:
                    return replace(item, loc=block.loc, bounds=block.kind)
                return item
            return hir.Void(block.loc)
        
        case '{}':
            if len(results) > 1:
                pdb.set_trace()
                return hir.Block(block.loc, ty.BlockType, results, scoped=True) #TODO: parameterize block type based on inner content... e.g. tuple of types
            if len(results) == 1:
                return hir.Block(block.loc, results[0].type, results, scoped=True)
            return hir.Void(block.loc)

        case '[]':
            if len(results) == 1 and isinstance(results[0], hir.Range) and results[0].bounds is None:
                return replace(results[0], loc=block.loc, bounds=block.kind)
            # otherwise it may be an array. also arrays should handle multi-dimensions via spacing, nested arrays, ;, etc.
            # might also be a generator...
            pdb.set_trace()
        case '[)':
            if len(results) != 1 or not isinstance(results[0], hir.Range) or results[0].bounds is not None:
                # TODO: full user error report
                raise ValueError(f'USER ERROR: [) delimiter for range may only contain one (bare range) expression, got {len(results)}. {results=}')
            return replace(results[0], loc=block.loc, bounds=block.kind)
        case '(]':
            if len(results) != 1 or not isinstance(results[0], hir.Range) or results[0].bounds is not None:
                # TODO: full user error report
                raise ValueError(f'USER ERROR: (] delimiter for range may only contain one (bare range) expression, got {len(results)}. {results=}')
            return replace(results[0], loc=block.loc, bounds=block.kind)
        case '<>':
            # return hir.TypeBlock(block.loc, type..., results) #TODO: handling type of type block based on contained inner items
            pdb.set_trace()
        case _:
            # unreachable
            raise ValueError(f'INTERNAL ERROR: invalid block kind: {block.kind}')
        
    # unreachable 
    pdb.set_trace()

def tcr_binop(binop: p0.BinOp, *, ctx: Context, type_block:bool=False) -> hir.AST:
    """
    typecheck and resolve a binary operator node.
    
    NOTE:
    type_block is used to disambiguate the context these binops occur in. 
    mainly for distinguishing type expressions using literals from regular operations between said literals
    e.g. `true | false` -> `true` vs `<true | false>` -> `literal<true>|literal<false>`
    most other operators are unaffected by this flag.
    """
    # TODO: how to handle the fact that `and` and `or` might have inner elements that need type_block? for now just pass in to left and right
    # full expression
    if isinstance(binop.op, (t2.QJuxtapose, t2.CallJuxtapose, t2.IndexJuxtapose, t2.MultiplyJuxtapose)): #TODO: other binops that also just do both sides
        left = typecheck_and_resolve_inner(binop.left, ctx=ctx, type_block=type_block)
        right = typecheck_and_resolve_inner(binop.right, ctx=ctx, type_block=type_block)
        match binop.op:
            case t2.QJuxtapose():
                pdb.set_trace()
            case t2.CallJuxtapose():
                # if isinstance(left, hir.AtHandle): return typecheck_partial_eval(left, right)
                return typecheck_function_call(left, right)
            case t2.IndexJuxtapose():
                pdb.set_trace()
            case t2.MultiplyJuxtapose():
                # TODO: need table for binop compatibility
                pdb.set_trace()
            case _:
                pdb.set_trace()
                raise NotImplementedError(f'tcr_binop not implemented for {type(binop.op)}')
        pdb.set_trace()



    # more specialized structures (e.g. assignment, spread, collect, parameterization, etc.)
    pdb.set_trace()


def typecheck_function_call(left: hir.AST, right: hir.AST) -> hir.Call:
    if not isinstance(left.type, ty.TypeFunc):
        # TODO: full user error report
        # might have some early errors for things that are function-like, but different instances.
        pdb.set_trace()
        raise ValueError(f'USER ERROR: Expected a function, got {left.type} for call expression {left=}, {right=}')
    
    
    if isinstance(right, hir.Block): 
        args = right.items
    else:
        args = [right]

    # verify the arguments given match that of the signature
    # TODO: more full type signature handling (named args, etc.)
    for call_arg, sig_arg in zip(args, left.type.args):
        if not ty.satisfies(call_arg.type, sig_arg):
            # TODO: full user error report
            pdb.set_trace()
            raise ValueError(f'USER ERROR: Argument {call_arg} does not match signature argument {sig_arg} for call expression {left=}, {right=}')

    return hir.Call(Span(left.loc.start, right.loc.stop), left.type.ret, left, args)


def typecheck_partial_eval(left: hir.AST, right: hir.AST) -> hir.Partial:
    pdb.set_trace()

def tcr_identifier(id: t1.Identifier, *, ctx: Context) -> hir.AST:
    if id.name in ctx.declarations:
        return hir.Identifier(id.loc, ctx.declarations[id.name], id.name)
    
    pdb.set_trace()
    raise NotImplementedError(f'Identifier "{id.name}" not found in context')


def test():
    from ...myargparse import ArgumentParser
    from pathlib import Path
    parser = ArgumentParser()
    parser.add_argument('path', type=Path, required=True, help='path to file to tokenize')
    args = parser.parse_args()
    path: Path = args.path
    src = path.read_text()
    srcfile = SrcFile(path, src)
    try:
        ast = typecheck_and_resolve(srcfile)
    except ReportException as e:
        print(e.report)
        exit(1)
    
    # TODO: some sort of tree print for HIR
    print(ast)
    
if __name__ == '__main__':
    test()