[book]
authors = ["David A. Samson"]
language = "en"
multilingual = false
src = "src"
title = "µDewy Language Specification"

[build]
build-dir = "book"

[output.html]
default-theme = "udewy-light"
preferred-dark-theme = "udewy-dark"
additional-css = ["theme/udewy-book.css"]
additional-js = ["theme/udewy-book.js"]
git-repository-url = "https://github.com/david-andrew/dewy-lang/tree/master/udewy"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/david-andrew/dewy-lang/edit/master/udewy/README.md"
site-url = "/udewy/reference/"
